:bug: fix(cineonu): use hashing to spot changes

diff --git a/.bin/cineonu-notifications b/.bin/cineonu-notifications
--- a/.bin/cineonu-notifications
+++ b/.bin/cineonu-notifications
@@ -7,20 +7,36 @@ ROOT="https://www.unric.org"
 LANG="en"
 BASEURI="${ROOT}/${LANG}"
 
+function log {
+	>&2 echo "$@"
+}
+
 if [ ! -f "${CONFIG}" ] ; then
-	>&2 echo "Missing config file @ ${CONFIG}"
+	log "Missing config file @ ${CONFIG}"
 	exit 2
 fi
 
 FROM="$(jq -r < "${CONFIG}" .mailfrom)"
 TO=$(jq -r < "${CONFIG}" .mailto[])
 
-function enqueue() {
+function hash {
+	xxhsum - <<< "$1" 2>/dev/null | head -c 16
+}
+
+function getmetadata() {
 	url="$(jq -r <<< "$1" .url)"
 	title="$(jq -r <<< "$1" .title)"
-	echo "${title} (${url})"
-	metadata="$(curl "${url}" | cineonu-parse-event)"
-	subject="New CINEONU event: ${title}"
+	log "Downloading ${title} (${url})"
+	curl "${url}" | cineonu-parse-event
+}
+
+function enqueue() {
+	kind="$1"
+	metadata="$2"
+	url="$(jq -r <<< "$metadata" .url)"
+	title="$(jq -r <<< "$metadata" .title)"
+	log "Enqueueing ${title} (${url})"
+	subject="${kind} CINEONU event: ${title}"
 
 	cineonu-event-format "${metadata}" | \
 	courriel.compose._prompt \
@@ -37,36 +53,42 @@ function main() {
 	year="$(date '+%Y')"
 
 	url="${BASEURI}/${year}"
-	storage="${CACHE}/${year}"
-	mkdir -p "${storage}"
+	storagedir="${CACHE}/${year}"
+	urldir="${storagedir}/url"
+	datdir="${storagedir}/dat"
 
-	next="${storage}/next.json"
-	prev="${storage}/prev.json"
+	mkdir -p "${urldir}"
+	mkdir -p "${datdir}"
 
-	if [ ! -f "${prev}" ] ; then
-		echo '{"events":[]}' > "${prev}"
-	fi
-
-	tmp="$(curl "${url}")"
+	html="$(curl "${url}")"
 
 	if [ "$?" -ne 0 ] ; then
 		exit 1
 	fi
 
-	<<< "${tmp}" cineonu-parse-list | jq > "${next}"
+	events="$(cineonu-parse-list <<< "${html}")"
 
 	run=0
-	diff="$(cineonu-list-diff "${prev}" "${next}")"
-	if [ -n "${diff}" ] ; then
-		while read -r event; do
+	while read -r event; do
+		metadata="$(getmetadata "${event}")"
+		url="$(jq -r <<< "$metadata" .url)"
+		dat_key="$(hash "$metadata")"
+		url_key="$(hash "$url")"
+		dat_file="${datdir}/${dat_key}"
+		url_file="${urldir}/${url_key}"
+		if [ ! -f "${dat_file}" ] ; then
 			run=1
-			enqueue "${event}"
-		done <<< "${diff}"
-	fi
+			kind=Updated
+			if [ ! -f "${url_file}" ] ; then
+				kind=New
+				echo "${url}" > "${url_file}"
+			fi
+			enqueue "${kind}" "${metadata}"
+			jq <<< "${metadata}" > "${dat_file}"
+		fi
+	done <<< "$(jq --compact-output '.events[]' <<< ${events})"
 
 	if [ "${run}" -gt 0 ] ; then msmtp-runqueue ; fi
-
-	mv "${next}" "${prev}"
 
 }
 
