emails: improve scripts
+ fix yn

diff --git a/.bin/msmtp-enqueue b/.bin/msmtp-enqueue
--- a/.bin/msmtp-enqueue
+++ b/.bin/msmtp-enqueue
@@ -1,20 +1,31 @@
 #!/usr/bin/env bash
 
-QUEUEDIR=$HOME/.msmtpqueue
+QUEUEDIR="$HOME/.msmtpqueue"
+LOCKFILE="$QUEUEDIR/.lock"
+SENDDELAY=2
 
 # Set secure permissions on created directories and files
 umask 077
 
-# Change to queue directory (create it if necessary)
-if [ ! -d "$QUEUEDIR" ]; then
-	mkdir -p "$QUEUEDIR" || exit 1
+echo "[=======] Greetings! This is msmtp-enqueue []_[]"
+echo "[=======] Running queue '$QUEUEDIR' with options '$OPTIONS'"
+
+# Jump to queue directory (create it if necessary)
+if ! mkdir -p "$QUEUEDIR" || ! cd "$QUEUEDIR" ; then
+	echo "[~~~~~~~] Cannot use '$QUEUEDIR' *_*"
+	exit 1
 fi
-cd "$QUEUEDIR" || exit 1
+
+echo "[=======] Waiting to acquire lockfile '$LOCKFILE' [<]"
+
+# wait for a lock that another instance might have set
+exec {LOCKFD}>"$LOCKFILE"
+flock -x "$LOCKFD"
 
 # Create new unique filenames of the form
 # MAILFILE:  ccyy-mm-dd-hh.mm.ss[-x].mail
 # MSMTPFILE: ccyy-mm-dd-hh.mm.ss[-x].msmtp
-# where x is a consecutive number only appended if you send more than one 
+# where x is a consecutive number only appended if you send more than one
 # mail per second.
 BASE="`date +%Y-%m-%d-%H.%M.%S`"
 if [ -f "$BASE.mail" -o -f "$BASE.msmtp" ]; then
@@ -29,15 +40,35 @@ MAILFILE="$BASE.mail"
 MSMTPFILE="$BASE.msmtp"
 
 # Write command line to $MSMTPFILE
-echo "$@" > "$MSMTPFILE" || exit 1
+if ! echo "$@" > "$MSMTPFILE" ; then
+	echo "[~~~~~~~] Could not write '$MSMTPFILE' *_*"
+	rm -f "$MSMTPFILE"
+	exit 1
+fi
 
 # Write the mail to $MAILFILE
-cat > "$MAILFILE" || exit 1
+if ! cat > "$MAILFILE" ; then
+	echo "[~~~~~~~] Could not write '$MAILFILE' *_*"
+	rm -f "$MSMTPFILE" "$MAILFILE"
+	exit 1
+fi
+
+echo "[SUCCESS] Your email has been added to the queue!"
+
+flock -u "$LOCKFD"
 
 # If we are online, run the queue immediately.
-ping -c 1 -w 2 8.8.8.8 > /dev/null
+ping -c 1 -w 2 8.8.4.4 > /dev/null
 if [ $? -eq 0 ]; then
-	msmtp-runqueue > /dev/null &
+	# Delay
+	if [ "$SENDDELAY" -gt 0 ] ; then
+		echo "[=======] Waiting $SENDDELAY seconds just to let you enough time to cancel that"
+	fi
+	delay "$SENDDELAY" msmtp-runqueue &
+else
+	echo "[*******] Could not ping 8.8.4.4 '_'"
+	echo "[*******] Do not worry though. Your email will eventually be sent"
+	echo "[*******] once the connection is back. Just run msmtp-runqueue again ^_^"
 fi
 
 exit 0
diff --git a/.bin/msmtp-runqueue b/.bin/msmtp-runqueue
--- a/.bin/msmtp-runqueue
+++ b/.bin/msmtp-runqueue
@@ -6,51 +6,54 @@ MAXWAIT=120
 
 OPTIONS=$@
 
-# wait for a lock that another instance has set
-WAIT=0
-while [ -e "$LOCKFILE" -a "$WAIT" -lt "$MAXWAIT" ]; do
-	sleep 1
-	WAIT="`expr "$WAIT" + 1`"
-done
-if [ -e "$LOCKFILE" ]; then
-	echo "Cannot use $QUEUEDIR: waited $MAXWAIT seconds for"
-	echo "lockfile $LOCKFILE to vanish, giving up."
-	echo "If you are sure that no other instance of this script is"
-	echo "running, then delete the lock file."
+echo "[=======] Greetings! This is msmtp-runqueue ()_()"
+echo "[=======] Running queue '$QUEUEDIR'"
+echo "[=======] With options '$OPTIONS'"
+
+# Jump to queue directory (create it if necessary)
+if ! mkdir -p "$QUEUEDIR" || ! cd "$QUEUEDIR" ; then
+	echo "[~~~~~~~] Cannot use '$QUEUEDIR' *_*"
 	exit 1
 fi
 
-# change into $QUEUEDIR 
-cd "$QUEUEDIR" || exit 1
+echo "[=======] Waiting $MAXWAIT seconds to acquire lockfile '$LOCKFILE' [<]"
+
+# wait for a lock that another instance might have set
+exec {LOCKFD}>"$LOCKFILE"
+if ! flock -x -w "$MAXWAIT" "$LOCKFD" ; then
+	echo "[~~~~~~~] Waited $MAXWAIT seconds for"
+	echo "[~~~~~~~] lockfile '$LOCKFILE', giving up -_-"
+	exit 1
+fi
+
+echo "[=======] Looking for emails to send ..( °°) [x]"
 
 # check for empty queuedir
 if [ "`echo *.mail`" = '*.mail' ]; then
-	echo "No mails in $QUEUEDIR"
+	echo "[=======] No emails in '$QUEUEDIR' è_é"
+	echo "[=======] Have a good day!"
 	exit 0
 fi
 
-# lock the $QUEUEDIR
-touch "$LOCKFILE" || exit 1
+echo "[=======] Sending emails that I found ^_^"
 
-# process all mails
+# process all emails
 for MAILFILE in *.mail; do
 	MSMTPFILE="`echo $MAILFILE | sed -e 's/mail/msmtp/'`"
-	echo "*** Sending $MAILFILE to `sed -e 's/^.*-- \(.*$\)/\1/' $MSMTPFILE` ..."
+	echo "[*******] Sending '$MAILFILE' to `sed -e 's/^.*-- \(.*$\)/\1/' $MSMTPFILE` ..."
 	if [ ! -f "$MSMTPFILE" ]; then
-		echo "No corresponding file $MSMTPFILE found"
-		echo "FAILURE"
+		echo "[FAILURE] Could not find '$MSMTPFILE' matching '$MAILFILE' :("
 		continue
 	fi
 	msmtp $OPTIONS `cat "$MSMTPFILE"` < "$MAILFILE"
 	if [ $? -eq 0 ]; then
 		rm "$MAILFILE" "$MSMTPFILE"
-		echo "$MAILFILE sent successfully"
+		echo "[SUCCESS] '$MAILFILE' sent successfully :)"
 	else
-		echo "FAILURE"
+		echo "[FAILURE] Could not send '$MAILFILE' :("
 	fi
 done
 
-# remove the lock
-rm -f "$LOCKFILE"
+echo "[=======] Reached the end of the queue. Have a good day!"
 
 exit 0
